services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=usuario_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d usuario_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Microservicio de Usuario
  servicio-user:
    build: 
      context: .
      dockerfile: ./servicios/usuario/Dockerfile
    container_name: servicio-user
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://user:pass@db:5432/usuario_db
    volumes:
      - ./servicios/usuario:/app
      - ./shared:/app/shared # Compartimos la carpeta shared
    depends_on:
      db:
        condition: service_healthy
  # Microservicio de Inventario
  servicio-inventario:
    build: 
      context: .
      dockerfile: ./servicios/inventario/Dockerfile
    container_name: servicio-inventario
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://user:pass@db:5432/usuario_db # Usamos la misma DB por ahora
    volumes:
      - ./servicios/inventario:/app
      - ./shared:/app/shared # Compartimos la carpeta shared
    depends_on:
      db:
        condition: service_healthy